Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus   = 2
  end

  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.vm.provision "file", source: "../setup/config", destination: "/tmp"
  config.vm.provision :shell, path: "../setup/scripts/bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8080
end
